name: Build the action

on: 
  push:

  pull_request: 

  workflow_dispatch:
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all