name: Publishing the action to the marketplace

on:   
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  test-local-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          user: rajbos
        id: load-actions

      - run: echo ${{ steps.load-actions.outputs.actions }} > 'actions.json'
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions
          path: actions.json
    
  publish:
    needs: test-local-action
    runs-on: ubuntu-latest
    steps:
      # get code
      - uses: actions/checkout@v2

      # build it
      - run: |
          npm ci
          npm run all    
      
      # generate SBOM for this project
      - name: CycloneDX Node.js Generate SBOM
        uses: CycloneDX/gh-node-module-generatebom@v1.0.0        

      - uses: actions/upload-artifact@v2
        with:
          path: bom.xml
          name: bom.xml

      # get tag for this release
      - name: Get tag value
        id: tag
        uses: rajbos-actions/action-get-tag@v1   

      # publish a release with the build assets
      - uses: rajbos-actions/action-gh-release@v1
        id: publish
        with:
          name: Release ${{ steps.tag.outputs.tag }}
          tag_name: ${{ github.ref }}
          body: Release ${{ steps.tag.outputs.tag }} is available now
          files: |
            ./dist/main.js 
            bom.xml
          token: ${{ secrets.PAT }}

      - run: |
          echo "$url"
        env:
          url: ${{ steps.publish.outputs.url }}

      - uses: rajbos-actions/slack@v1
        with: 
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
